apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: testacivic.azurecr.io/azvote/azure-vote-front
    newTag: f4ffcea9f9d8fa1e75884e8a48cb9b7691418a3d
  - name: testacivic.azurecr.io/azvote/azure-vote-back
    newTag: f4ffcea9f9d8fa1e75884e8a48cb9b7691418a3d
resources:
  - manifests.yaml