apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: testacivic.azurecr.io/azvote/azure-vote-front
    newTag: c2e5e0049a3d2eb435ba6c746b9ab24ff70d1a99
  - name: testacivic.azurecr.io/azvote/azure-vote-back
    newTag: c2e5e0049a3d2eb435ba6c746b9ab24ff70d1a99
resources:
  - manifests.yaml